sonar.projectKey=JoseArthurCamiloDosAnjos_PI_MERCADINS
sonar.organization=josearthurcamilo-dos-anjos

sonar.sources=Frontend/src,Backend/src

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

sonar.sourceEncoding=UTF-8
